on:
  push:
    branches:
      - main
  workflow_dispatch:

name: cachix-debug

jobs:
  ci:
    runs-on: nscloud
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json
          uname -a
      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: ns
          authToken: "test"

  ci-gh-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json
          uname -a
      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: ns
          authToken: "test"
