on: [workflow_dispatch]

name: nsl3646

jobs:
  ci:
    runs-on:
      - namespace-profile-test-nsl-3646
    steps:
      - uses: actions/checkout@v4
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - run: |
          DOCKER_BUILDKIT=1 docker buildx build --provenance false --pull --push --platform linux/amd64 --cache-to type=inline --cache-from type=registry,ref=ghcr.io/nsfoundation/testdocker:latest -t ghcr.io/nsfoundation/testdocker:latest -t ghcr.io/nsfoundation/testdocker:latest -f ./Dockerfile .
      
