on:
  workflow_dispatch:

name: shared-daemon

jobs:
  start-poke:
    runs-on: nscloud
    steps:
      - name: Start nginx
        run: |
          docker run -d --network=host nginx
          docker ps
          curl http://localhost:80
      - name: Poke nginx
        run: |
          curl http://localhost:80
