on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      breakpoint:
        description: "Stop for debugging"
        required: false
        type: boolean
      run_on_ghrunners:
        description: "Also run on GitHub-hosted runners"
        required: false
        type: boolean

name: simple-macos

jobs:
  ci:
    runs-on: namespace-profile-macos
    steps:
      - name: Env checks
        run: |
          ulimit -a
          env
          uname -a
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          check-latest: true
      - name: Install Yarn dependencies
        run: |
          # Deals with yarn (v1) install flakiness
          yarn || yarn --network-concurrency 1
          # Another install flakiness fix (at least in yarn v1 with node 20)
          # yarn postinstall isn't always run (?!) so we run it manually
          yarn postinstall
        shell: bash
      - name: Breakpoint
        if: inputs.breakpoint || failure() && github.ref_name == 'main'
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 15m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo,attilaolah,pavolmarko

  ghrunners:
    runs-on: macos-14
    if: inputs.run_on_ghrunners
    steps:
      - name: Env checks
        run: |
          ulimit -a
          env
          uname -a
