on: [push, workflow_dispatch]

name: simple

jobs:
  ci:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-2x4
      - nscloud-exp-features:privileged;host-cgroup-namespace
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json
          uname -a

      - name: Breakpoint
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 5m
          authorized-users: edganiukov,nichtverstehen

  ci-gh-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Env checks
        run: |
          ulimit -a
          aws --version
          docker buildx ls 
          env
          cat ~/.docker/config.json
          uname -a
