on:
  push:
    branches:
      - main
  workflow_dispatch:

name: simple-macos

jobs:
  ci:
    runs-on: namespace-profile-macos
    steps:
      - name: Env checks
        run: |
          ulimit -a
          env
          uname -a

  macv2:
    runs-on: namespace-profile-macv2
    steps:
      - name: Env checks
        run: |
          ulimit -a
          env
          uname -a

  ghrunners:
    runs-on: macos-14
    steps:
      - name: Env checks
        run: |
          ulimit -a
          env
          uname -a
