on:
  push:
    branches:
      - main
  workflow_dispatch:

name: simple-macos

jobs:
  ci:
    runs-on: namespace-profile-macos
    steps:
      - name: Env checks
        run: |
          ulimit -a
          env
          uname -a

  ghrunners:
    runs-on: macos-14
    steps:
      - name: Env checks
        run: |
          ulimit -a
          env
          uname -a
      - name: Breakpoint
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: nichtverstehen
