on: [push, workflow_dispatch]

name: simple-macos

jobs:
  ci:
    runs-on: namespace-profile-macos
    steps:
      - name: Env checks
        run: |
          ulimit -a
          env
          uname -a
