on: [push, workflow_dispatch]

name: With Volume

jobs:
  main:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-2x4-with-cache
      - nscloud-cache-tag-testdocker-with-volume
      - nscloud-cache-size-10gb
      - nscloud-exp-container-image-cache
      - nscloud-exp-runner-tool-cache-5gb
      - nscloud-git-mirror-5gb
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        run: |
          ls /cache/
          touch "/cache/$(date -Idate).txt"
