on: [push, workflow_dispatch]

name: With Cache

jobs:
  ci:
    runs-on: nscloud
    steps:
      - run: env

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure access to Namespace
        uses: namespacelabs/nscloud-setup@v0

      - name: Save cache
        id: cache-large-file
        uses: namespacelabs/nscloud-cache-action@v0
        with:
          key: large-file-${{github.sha}}
          path: 200MB.zip

      - name: Download large file
        run: |
          wget http://212.183.159.230/200MB.zip
        if: steps.cache-large-file.outputs.cache-hit != 'true'

      - name: Use large file
        run: |
          ls -l 200MB.zip
          shasum 200MB.zip
