on:
  push:
    branches:
      - main
  workflow_dispatch:

name: With Container

jobs:
  on-nscloud:
    runs-on: nscloud
    container:
      image: debian:bullseye
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: hello
        run: |
          echo Hello from container

  on-github:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: hello
        run: |
          echo Hello from container
