on:
  push:
    branches:
      - main
  workflow_dispatch:

name: With Volume

jobs:
  main:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-2x4-with-cache
      - nscloud-cache-tag-testdocker-with-volume
      - nscloud-cache-size-10gb
      - nscloud-exp-container-image-cache
      - nscloud-exp-runner-tool-cache-5gb
      - nscloud-git-mirror-5gb
    steps:
      - uses: actions/checkout@v3

      - name: Touch
        run: |
          ls "$NSC_CACHE_PATH"
          touch "$NSC_CACHE_PATH/$(date -Iseconds).txt"

      - name: Mount cache
        id: cache-downloads
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: downloads

      - name: Download large file
        run: |
          wget -P downloads http://ipv4.download.thinkbroadband.com/200MB.zip
        if: steps.cache-downloads.outputs.cache-hit != 'true'

      - name: Use large file
        run: |
          ls -l downloads/200MB.zip
          shasum downloads/200MB.zip
